"""Initial migration

Revision ID: 68a8e3b11195
Revises: 
Create Date: 2025-05-28 16:22:43.003164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a8e3b11195'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Controlli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolo_controllo', sa.String(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=False),
    sa.Column('controllo_comune', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("""
           INSERT INTO Controlli (id, titolo_controllo, descrizione, controllo_comune)
           VALUES
           (1, 'Controllo olio', 'Verifica livello e qualità olio motore', 1),
           (2, 'Controllo freni', 'Ispezione sistema frenante', 1),
           (3, 'Controllo pneumatici', 'Verifica usura gomme e pressione', 0)
       """)

    op.create_table('Dipendenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cognome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.execute(
        """
        INSERT INTO Dipendenti (id,nome,cognome,email,username, hashed_password, admin)
        VALUES (1,'Marco','Paschetta','admin@admin.ad', 'admin', '$2b$12$Fyp.CIuqwcrqs09Oklz71eVMcwHBTP11x3FBj.B6LiUl7dxEYuaO2', true)
        """
    )

    op.create_table('Macchine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('telaio', sa.String(), nullable=False),
    sa.Column('data_arrivo', sa.Date(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telaio')
    )

    op.execute("""
           INSERT INTO Macchine (id, nome, anno, telaio, data_arrivo, marca)
           VALUES 
           (1, 'Clio', 2022, 'ZFA12345678901234', '2024-01-15', 'Renault'),
           (2, 'Captur', 2023, 'ZFA98765432109876', '2024-02-20', 'Renault')
       """)

    op.create_table('MacchineControlli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_macchina', sa.Integer(), nullable=False),
    sa.Column('id_controllo', sa.Integer(), nullable=False),
    sa.Column('completato', sa.Boolean(), nullable=False),
    sa.Column('utente', sa.String(), nullable=False),
    sa.Column('commento', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_controllo'], ['Controlli.id'], ),
    sa.ForeignKeyConstraint(['id_macchina'], ['Macchine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("""
           INSERT INTO MacchineControlli (id, id_macchina, id_controllo, completato, utente, commento)
           VALUES
           (1, 1, 1, 1, 'Marco Paschetta', 'Olio sostituito regolarmente'),
           (2, 2, 2, 0, 'Marco Paschetta', 'Freni da controllare a breve')
       """)

    op.create_table('Magazzino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_macchina', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_macchina'], ['Macchine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("""
          INSERT INTO Magazzino (id, id_macchina, costo)
          VALUES
          (1, 1, 150),
          (2, 2, 200)
      """)

    op.create_table('Vendite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_macchina', sa.Integer(), nullable=False),
    sa.Column('data_vendita', sa.Date(), nullable=False),
    sa.Column('compratore', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_macchina'], ['Macchine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.execute("""
           INSERT INTO Vendite (id, id_macchina, data_vendita, compratore)
           VALUES
           (1, 1, '2024-04-10', 'Mario Rossi')
       """)

    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vendite')
    op.drop_table('Magazzino')
    op.drop_table('MacchineControlli')
    op.drop_table('Macchine')
    op.drop_table('Dipendenti')
    op.drop_table('Controlli')
    # ### end Alembic commands ###
